---
- name: vcenter_create_from_template
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars_common.yml

# execute example:
# ansible-playbook vcenter_create_from_template.yml -e '{"vcenter_hostname":"192.168.1.250","vcenter_username":"administrator@vsphere.local","vcenter_password":"SHqz8866.","vm_name":"centos7_192.168.1.67","datacenter":"Datacenter","esxi_hostname":"192.168.1.161","annotation":"ansible auto created, IP: 192.168.1.67","num_cpus":"8","num_cpu_cores_per_socket":"1","memory_mb":"8192","disk_size_gb":"100","disk_type":"thin","disk_datastore":"datastore_161","networks_name":"VM Network","networks_type":"static","ip":"192.168.1.67","netmask":"255.255.255.0","gateway":"192.168.1.1","hostname":"shqz-67","dns1":"192.168.1.1","dns2":"114.114.114.114","template":"centos7_template_0228"}'

  roles:
    - vcenter_create_from_template
