---
- name: change state to powered-off
  vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "/Datacenter/vm/"
    name: "{{ vm_name }}"
    state: "powered-off"
  delegate_to: localhost

- name: delete VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    esxi_hostname: "{{ esxi_hostname }}"
    state: absent
  delegate_to: localhost
...