---
- name: snapshot managerment
  vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    folder: "/Datacenter/vm/"
    name: "{{ vm_name }}"
    state: "{{ state }}"
    snapshot_name: "{{ snapshot_name }}"
    description: "{{ description }}"
  delegate_to: localhost
...